#clear all current variables or functions from R memory and start (or restart) script/anayses
rm(list = ls(all = TRUE)) 

###### Howell Puerto Rican Anole Toe Pad Shape Linear Analyses ######

  #In addition to our high dimensional analyses (PCA, bgPCA, CVA), we extracted linear measurements from 
  #our raw-unaligned toe pad landmarks in millimeters, to use for traditional linear morphometric analyses 
  #We used linear measurements from our raw unaligned data because that data has not been increased or decreased in size 
  #and we can use it to infer changes in toe pad length and width, testing our hypotheses of non-isometric change


  ## Please run the "Howell PR Preliminary Data Setup.R" script prior to this script.
  ## It generates the required "Howell R data.Rdata" file needed for these analyses

## Necessry files for this R script

  # Howell R data.Rdata - generated by the "Howell PR Preliminary Data Setup.R" script 

## Packages used in this script 

  #library(geomorph)
  packageVersion("geomorph")
  #3.3.1

  #library(car)
  packageVersion("car")
  #3.0.2
  
## Custom functions used in this script 


## My Current R and RStudio Versions 

  #check version of R
  getRversion()
  #R version 3.5.3

  #check R studio version
  require(rstudioapi)
  versionInfo()$version
  #RStudio version 1.1.463

######
###### Retrieving Linear Measurements ######

#Load geomoprh libary
library(geomorph)

#Set working directory
### CHANGE THIS if not already in correct working directory ###
setwd("UrbanToepadShape")

load(file="Howell R data.Rdata") #Load the previously generated data file. 

#Save the imported datasets to their own objects
dat.raw<-Howell_dat$dat.raw
dat.field<-Howell_dat$dat.field 

#Set relevant variables as factors 
dat.field$Habitat_Category<-as.factor(dat.field$Habitat_Category)
dat.field$Municipality<-as.factor(dat.field$Municipality)

##Extract linear measuremetns from raw landmark data. These measurements are in millimeters 
#Make a matrix to recieve linear measurements for each indiviudal 
dat.linear.raw<-matrix(nrow=dim(dat.raw)[3], ncol=6)
colnames(dat.linear.raw)<-c("padwidth", "padlength", "proxtoelength", "avelamwidth", "totaltoelength", "pad_W/L")
rownames(dat.linear.raw)<-names(dat.raw[1,1,])

for (i in 1:nrow(dat.linear.raw)){
  #i<-1
  dat.linear.raw[i,"padwidth"]<-dist(dat.raw[5:6,,i], method = "euclidean") #pad width (distance between landmarks 5 and 6)
  pt2<-apply(dat.raw[3:4,,i], MARGIN=2, FUN = mean) #center of pad base (average of landmark 3 and 4)
  pt3<-apply(dat.raw[7:8,,i], MARGIN=2, FUN = mean) #center of distal pad (average of landamrk 7 an 8)
  dat.linear.raw[i,"padlength"]<-dist(rbind(pt3, pt2), method = "euclidean") #distance between the center of the top and the center of the bottom of the pad
  
  pt1<-apply(dat.raw[1:2,,i], MARGIN=2, FUN =mean) #center of toe base (average of landamrks 1 and 2)
  dat.linear.raw[i,"proxtoelength"]<-dist(rbind(pt1, pt2), method = "euclidean") #distance from center of toe base to pad base
  
  #distances between the sides of the lamellae 5-10
  d1L<-dist(dat.raw[c(10,12),,i], method = "euclidean") #distance between landmakrs 10 and 12
  d1R<-dist(dat.raw[c(11,13),,i], method = "euclidean") #distance between landmakrs 11 and 13
  d2L<-dist(dat.raw[c(12,14),,i], method = "euclidean") #etc
  d2R<-dist(dat.raw[c(13,15),,i], method = "euclidean") #etc
  d3L<-dist(dat.raw[c(14,16),,i], method = "euclidean")
  d3R<-dist(dat.raw[c(15,17),,i], method = "euclidean")
  d4L<-dist(dat.raw[c(16,18),,i], method = "euclidean")
  d4R<-dist(dat.raw[c(17,19),,i], method = "euclidean")
  dat.linear.raw[i,"avelamwidth"]<-mean(d1L, d1R, d2L, d2R, d3L, d3R, d4L, d4R) #average lamellae width, across all 5 lamelale left and right sides

  #total toe length
  dat.linear.raw[i, "totaltoelength"]<-dat.linear.raw[i,"padlength"]+dat.linear.raw[i,"proxtoelength"]
  
  #pad width / length ratio 
  dat.linear.raw[i, "pad_W/L"]<-dat.linear.raw[i,"padwidth"]/dat.linear.raw[i,"padlength"]
  
}

#check to make sure our individuals are all in the same order across our three datasets 
rownames(dat.linear.raw)==dat.field$Specimen #yes

#remove variables we no logner need 
rm(dat.raw)
rm(Howell_dat)
rm(d1L)
rm(d1R)
rm(d2L)
rm(d2R)
rm(d3L)
rm(d3R)
rm(d4L)
rm(d4R)
rm(i)
rm(pt1)
rm(pt2)
rm(pt3)


###### Linear Pad Width and Length Stats and Plots #####
#ask if the mean width/length ratio of urban and forest populations are significantly different 
out<-t.test(log(dat.linear.raw[dat.field$Habitat_Category=="urban","pad_W/L"]), log(dat.linear.raw[dat.field$Habitat_Category=="forest","pad_W/L"]))
out #yes, the means are signifincalty different p-value = 0.04104
out$statistic #t value -2.054613 
out$parameter #df 230.9853
out$p.value  #0.04104172

exp(out$estimate[1]) # 0.5145263 urban
exp(out$estimate[2]) # 0.5265281 forest

#get 95% confidence intervals 
CI<-t.test(log(dat.linear.raw[dat.field$Habitat_Category=="forest","pad_W/L"]), conf.level = 0.95)$conf.int[1:2]
exp(CI) #between 0.5178003 and 0.5354030


CI<-t.test(log(dat.linear.raw[dat.field$Habitat_Category=="urban","pad_W/L"]), conf.level = 0.95)$conf.int[1:2]
exp(CI) #between 0.5070470 0.5221159


#How much longer or wider are urban pads as comapred to forest pads? 
mean(dat.linear.raw[dat.field$Habitat_Category=="urban", "padwidth"]) #1.863026mm
sd(dat.linear.raw[dat.field$Habitat_Category=="urban", "padwidth"]) #0.2792379
mean(dat.linear.raw[dat.field$Habitat_Category=="urban", "padlength"]) #3.608004mm
sd(dat.linear.raw[dat.field$Habitat_Category=="urban", "padlength"]) #0.4671754

mean(dat.linear.raw[dat.field$Habitat_Category=="forest", "padwidth"]) #1.692725mm
sd(dat.linear.raw[dat.field$Habitat_Category=="forest", "padwidth"]) #0.2676026
mean(dat.linear.raw[dat.field$Habitat_Category=="forest", "padlength"]) #3.201738mm
sd(dat.linear.raw[dat.field$Habitat_Category=="forest", "padlength"]) #0.4272731


mean(dat.linear.raw[dat.field$Habitat_Category=="urban", "padwidth"])/mean(dat.linear.raw[dat.field$Habitat_Category=="forest", "padwidth"])
#1.100608 meaning urban pads are 10.06% wider

mean(dat.linear.raw[dat.field$Habitat_Category=="urban", "padlength"])/mean(dat.linear.raw[dat.field$Habitat_Category=="forest", "padlength"])
#1.126889 meaning urban pads are 12.7% longer


#Plots 
#make transparent urban grey colors for histograms
grey.transparant<-rgb(t(col2rgb("darkgrey")/255), alpha = 0.5)

#histogram comparison of the W/L ratios 
pdf(file=file.path("Output/Plots/Linear/Width-Length Hist.pdf"), width=4, height=2)
par(mar=c(2.5,3.5,0,1)) 

brks<-seq(from=0.35, to=0.75, by=0.02)
hist((dat.linear.raw[,"pad_W/L"]), breaks=brks, border = "white", xaxt="n", xlab=NA, ylab=NA, main=NA, ylim=c(0, 35))
abline(v=exp(out$estimate[1]), col="darkgrey", lwd=3)
abline(v=exp(out$estimate[2]), col="darkgreen", lwd=3)
hist(dat.linear.raw[dat.field$Habitat_Category=="forest","pad_W/L"], breaks=brks, col="darkgreen", add=T)
hist((dat.linear.raw[dat.field$Habitat_Category=="urban","pad_W/L"]), breaks=brks, col=grey.transparant, add=T)

mtext("Ratio of Pad Width/Pad Length", side=1, line=1.2, cex=1.5)
mtext("Count", side=2, line=2, cex=1.5)

axis(side = 1, line = -0.3, at = c(0.4, 0.5, 0.6, 0.7), padj = -1)
abline(h=0)

legend("topright", legend=c("Forest Lizards", "Urban Lizards"), fill=c("darkgreen", grey.transparant), bty="n", border="black")

text(x=0.33, y=35, labels = paste(" t = ", signif(out$statistic, digits = 3)), cex = 0.6, pos=4 )
text(x=0.33, y=32, labels = paste("df = ", round(out$parameter, digits = 1)), cex = 0.6, pos=4 )
text(x=0.33, y=29, labels = paste(" p = ", round(out$p.value, digits = 3)), cex = 0.6, pos=4, font = 2)

dev.off()


#Width vs Length Scatter Plot
green.transparant<-"#00800080" #transparnt green
grey.transparant<-"#BEBEBE80" #transparant grey

HabColors<-as.character(dat.field$Habitat_Category)
HabColors[HabColors=="urban"]<-grey.transparant
HabColors[HabColors=="forest"]<-green.transparant


pdf(file=file.path("Output/Plots/Linear/Width-Length scatter.pdf"), width=4, height=4)
par(mar=c(2.5,3.5,0,1), pty="s") 

plot(dat.linear.raw[,"padlength"], dat.linear.raw[,"padwidth"], col="white", pch=19, xlab=NA, ylab=NA, asp=1, xlim=c(1.5,5))
abline(lm(dat.linear.raw[dat.field$Habitat_Category=="forest","padwidth"]~0+dat.linear.raw[dat.field$Habitat_Category=="forest","padlength"]), col=green.transparant, lwd=3)
abline(lm(dat.linear.raw[dat.field$Habitat_Category=="urban","padwidth"]~0+dat.linear.raw[dat.field$Habitat_Category=="urban","padlength"]), col=grey.transparant, lwd=3)

hpts<-chull(dat.linear.raw[dat.field$Habitat_Category=="forest","padlength"], dat.linear.raw[dat.field$Habitat_Category=="forest","padwidth"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(dat.linear.raw[dat.field$Habitat_Category=="forest","padlength"][hpts], dat.linear.raw[dat.field$Habitat_Category=="forest","padwidth"][hpts], col=green.transparant) #plot the lines

hpts<-chull(dat.linear.raw[dat.field$Habitat_Category=="urban","padlength"], dat.linear.raw[dat.field$Habitat_Category=="urban","padwidth"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(dat.linear.raw[dat.field$Habitat_Category=="urban","padlength"][hpts], dat.linear.raw[dat.field$Habitat_Category=="urban","padwidth"][hpts], col=grey.transparant) #plot the lines

points(dat.linear.raw[,"padlength"], dat.linear.raw[,"padwidth"], col=HabColors, pch=19)

#Muni urban and forest averages 
pt1<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Aguadilla", "padlength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Aguadilla", "padwidth"]))
pt2<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Aguadilla", "padlength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Aguadilla", "padwidth"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="grey", col="black", pch=24)
points(pt2[1], pt2[2], bg="darkgreen", col="black", pch=24)

pt1<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Arecibo", "padlength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Arecibo", "padwidth"]))
pt2<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Arecibo", "padlength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Arecibo", "padwidth"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="grey", col="black", pch=23)
points(pt2[1], pt2[2], bg="darkgreen", col="black", pch=23)

pt1<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Mayaguez", "padlength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Mayaguez", "padwidth"]))
pt2<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Mayaguez", "padlength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Mayaguez", "padwidth"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="grey", col="black", pch=21)
points(pt2[1], pt2[2], bg="darkgreen", col="black", pch=21)

pt1<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Ponce", "padlength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Ponce", "padwidth"]))
pt2<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Ponce", "padlength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Ponce", "padwidth"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="grey", col="black", pch=22)
points(pt2[1], pt2[2], bg="darkgreen", col="black", pch=22)

pt1<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "San Juan", "padlength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "San Juan", "padwidth"]))
pt2<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "San Juan", "padlength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "San Juan", "padwidth"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="grey", col="black", pch=25)
points(pt2[1], pt2[2], bg="darkgreen", col="black", pch=25)


mtext("Pad Length (mm)", side=1, line=2.4, cex=1.5)
mtext("Pad Width (mm)", side=2, line=2, cex=1.5)


legend(x=4.15, y=3.62, pch=c(24,23,21,22,25), legend=rep("", 5), pt.bg="darkgreen", bty="n", cex=0.6)
legend(x=4.3, y=3.62, pch=c(24,23,21,22,25), pt.bg="grey", legend=c("Aguadilla", "Arecibo", "Mayaguez", "Ponce", "San Juan"), bty="n", cex=0.6)
text(4.41, 3.62, "Forest", cex=0.6, pos=2, xpd=T)
text(4.8, 3.62, "Urban", cex=0.6, pos=2, xpd=T)

dev.off()


#add bar plots to side 1 and side 2
pdf(file=file.path("Output/Plots/Linear/Width-Length scatter_Xbar.pdf"), width=4, height=1.5)
par(mar=c(2.5,1,1,3)) 

brks<-seq(2,5,0.25)
hist(dat.linear.raw[,"padlength"], main=NA, breaks=brks, border="white", xlab=NA, ylab=NA, yaxt="n", ylim=c(0,40))

hist(dat.linear.raw[dat.field$Habitat_Category=="forest","padlength"], breaks=brks, col="darkgreen", add=T)
hist((dat.linear.raw[dat.field$Habitat_Category=="urban","padlength"]), breaks=brks, col=grey.transparant, add=T)
mtext("Count", side=4, line=1.5, cex=1)

axis(side = 4, at = c(0, 20, 40), padj = -1)
dev.off()


pdf(file=file.path("Output/Plots/Linear/Width-Length scatter_Ybar.pdf"), width=4, height=1.25)
par(mar=c(2.5,1,1,3)) 

brks<-seq(0.5,3,0.25)
hist(dat.linear.raw[,"padwidth"], main=NA, breaks=brks, border="white", xlab=NA, ylab=NA, yaxt="n", ylim=c(0,60))

hist(dat.linear.raw[dat.field$Habitat_Category=="forest","padwidth"], breaks=brks, col="darkgreen", add=T)
hist((dat.linear.raw[dat.field$Habitat_Category=="urban","padwidth"]), breaks=brks, col=grey.transparant, add=T)
mtext("Count", side=4, line=1.5, cex=1)

axis(side = 4, at = c(0, 30, 60), padj = -1)
dev.off()


#For each Municipality, make its own width vs length plot, with lines through the origin to show its expected isometric change (forest line) vs its urban ratio, with forest and urban means and segments 

pdf(file=file.path("Output/Plots/Linear/supp/Width-Length scatter_Municipality_sep.pdf"), width=10, height=3)
par(mfrow=c(1,5), mar=c(4,4,2,0.5), pty="s")


#Aguadilla
forest.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Aguadilla", "padlength"], dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Aguadilla", "padwidth"])
urban.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Aguadilla", "padlength"], dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Aguadilla", "padwidth"])

plot(dat.linear.raw[,"padlength"], dat.linear.raw[,"padwidth"], col="white", pch=19, xlab=NA, ylab=NA, asp=1)
abline(lm(forest.pts[,2]~0+forest.pts[,1]), col=green.transparant, lwd=3)
abline(lm(urban.pts[,2]~0+urban.pts[,1]), col=grey.transparant, lwd=3)

hpts<-chull(forest.pts[,2], forest.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[hpts,1], forest.pts[hpts,2], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[,2], urban.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[hpts,1], urban.pts[hpts,2], col=grey.transparant) #plot the lines

points(forest.pts, bg=green.transparant, col=NA, pch=24, cex=1.2)
points(urban.pts, bg=grey.transparant, col=NA, pch=24, cex=1.2)

#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,1]), mean(forest.pts[,2]))
pt2<-c(mean(urban.pts[,1]), mean(urban.pts[,2]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=24)
points(pt2[1], pt2[2], bg="gray", col="black", pch=24)

mtext("Pad Length (mm)", side=1, line=2.4, cex=1)
mtext("Pad Width (mm)", side=2, line=2, cex=1)
mtext("Aguadilla", side=3, line=0.5, font=2, cex=1)


#Arecibo
forest.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Arecibo", "padlength"], dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Arecibo", "padwidth"])
urban.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Arecibo", "padlength"], dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Arecibo", "padwidth"])

plot(dat.linear.raw[,"padlength"], dat.linear.raw[,"padwidth"], col="white", pch=19, xlab=NA, ylab=NA, asp=1)
abline(lm(forest.pts[,2]~0+forest.pts[,1]), col=green.transparant, lwd=3)
abline(lm(urban.pts[,2]~0+urban.pts[,1]), col=grey.transparant, lwd=3)

hpts<-chull(forest.pts[,2], forest.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[hpts,1], forest.pts[hpts,2], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[,2], urban.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[hpts,1], urban.pts[hpts,2], col=grey.transparant) #plot the lines

points(forest.pts, bg=green.transparant, col=NA, pch=23, cex=1.2)
points(urban.pts, bg=grey.transparant, col=NA, pch=23, cex=1.2)

#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,1]), mean(forest.pts[,2]))
pt2<-c(mean(urban.pts[,1]), mean(urban.pts[,2]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=23)
points(pt2[1], pt2[2], bg="gray", col="black", pch=23)

mtext("Pad Length (mm)", side=1, line=2.4, cex=1)
mtext("Pad Width (mm)", side=2, line=2, cex=1)
mtext("Arecibo", side=3, line=0.5, font=2, cex=1)


#Mayaguez
forest.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Mayaguez", "padlength"], dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Mayaguez", "padwidth"])
urban.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Mayaguez", "padlength"], dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Mayaguez", "padwidth"])

plot(dat.linear.raw[,"padlength"], dat.linear.raw[,"padwidth"], col="white", pch=19, xlab=NA, ylab=NA, asp=1)
abline(lm(forest.pts[,2]~0+forest.pts[,1]), col=green.transparant, lwd=3)
abline(lm(urban.pts[,2]~0+urban.pts[,1]), col=grey.transparant, lwd=3)

hpts<-chull(forest.pts[,2], forest.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[hpts,1], forest.pts[hpts,2], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[,2], urban.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[hpts,1], urban.pts[hpts,2], col=grey.transparant) #plot the lines

points(forest.pts, bg=green.transparant, col=NA, pch=21, cex=1.2)
points(urban.pts, bg=grey.transparant, col=NA, pch=21, cex=1.2)

#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,1]), mean(forest.pts[,2]))
pt2<-c(mean(urban.pts[,1]), mean(urban.pts[,2]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=21)
points(pt2[1], pt2[2], bg="gray", col="black", pch=21)

mtext("Pad Length (mm)", side=1, line=2.4, cex=1)
mtext("Pad Width (mm)", side=2, line=2, cex=1)
mtext("Mayaguez", side=3, line=0.5, font=2, cex=1)



#Ponce
forest.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Ponce", "padlength"], dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Ponce", "padwidth"])
urban.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Ponce", "padlength"], dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Ponce", "padwidth"])

plot(dat.linear.raw[,"padlength"], dat.linear.raw[,"padwidth"], col="white", pch=19, xlab=NA, ylab=NA, asp=1)
abline(lm(forest.pts[,2]~0+forest.pts[,1]), col=green.transparant, lwd=3)
abline(lm(urban.pts[,2]~0+urban.pts[,1]), col=grey.transparant, lwd=3)

hpts<-chull(forest.pts[,2], forest.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[hpts,1], forest.pts[hpts,2], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[,2], urban.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[hpts,1], urban.pts[hpts,2], col=grey.transparant) #plot the lines

points(forest.pts, bg=green.transparant, col=NA, pch=22, cex=1.2)
points(urban.pts, bg=grey.transparant, col=NA, pch=22, cex=1.2)

#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,1]), mean(forest.pts[,2]))
pt2<-c(mean(urban.pts[,1]), mean(urban.pts[,2]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=22)
points(pt2[1], pt2[2], bg="gray", col="black", pch=22)

mtext("Pad Length (mm)", side=1, line=2.4, cex=1)
mtext("Pad Width (mm)", side=2, line=2, cex=1)
mtext("Ponce", side=3, line=0.5, font=2, cex=1)



#San Juan
forest.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "San Juan", "padlength"], dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "San Juan", "padwidth"])
urban.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "San Juan", "padlength"], dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "San Juan", "padwidth"])

plot(dat.linear.raw[,"padlength"], dat.linear.raw[,"padwidth"], col="white", pch=19, xlab=NA, ylab=NA, asp=1)
abline(lm(forest.pts[,2]~0+forest.pts[,1]), col=green.transparant, lwd=3)
abline(lm(urban.pts[,2]~0+urban.pts[,1]), col=grey.transparant, lwd=3)

hpts<-chull(forest.pts[,2], forest.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[hpts,1], forest.pts[hpts,2], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[,2], urban.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[hpts,1], urban.pts[hpts,2], col=grey.transparant) #plot the lines

points(forest.pts, bg=green.transparant, col=NA, pch=25, cex=1.2)
points(urban.pts, bg=grey.transparant, col=NA, pch=25, cex=1.2)

#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,1]), mean(forest.pts[,2]))
pt2<-c(mean(urban.pts[,1]), mean(urban.pts[,2]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=25)
points(pt2[1], pt2[2], bg="gray", col="black", pch=25)

mtext("Pad Length (mm)", side=1, line=2.4, cex=1)
mtext("Pad Width (mm)", side=2, line=2, cex=1)
mtext("San Juan", side=3, line=0.5, font=2, cex=1)


dev.off()



#remove variables we no logner need 
rm(forest.pts)
rm(urban.pts)
rm(out)
rm(brks)
rm(HabColors)
rm(hpts)
rm(pt1)
rm(pt2)
rm(CI)

###### Linear Toe Proportions Stats and Plots #####
#ask how the proportions of the toe (ie how the total length of the toe and the proportion of the toe that is pad)
#has changed in urban lizards. 

#First ask if total toe length has changed in urban lizards 
out<-t.test(log(dat.linear.raw[dat.field$Habitat_Category=="urban","totaltoelength"]), log(dat.linear.raw[dat.field$Habitat_Category=="forest","totaltoelength"]))
out #yes, the means are significantly different p-value = 4.637e-08
out$statistic #t value 5.661712
out$parameter #df 220.6477
out$p.value  #4.636604e-08

exp(out$estimate[1]) #10.59494 urban
exp(out$estimate[2]) #9.806026 forest

#get 95% confidence intervals 

CI<-t.test(log(dat.linear.raw[dat.field$Habitat_Category=="forest","totaltoelength"]), conf.level = 0.95)$conf.int[1:2]
exp(CI) #between 9.601003 and 10.015427

CI<-t.test(log(dat.linear.raw[dat.field$Habitat_Category=="urban","totaltoelength"]), conf.level = 0.95)$conf.int[1:2]
exp(CI) #between 10.41725 and 10.77566



#Plots
#histogram comparison of total toe lengths 
pdf(file=file.path("Output/Plots/Linear/Toe Length Hist.pdf"), width=6, height=1.5)
par(mar=c(2.5,1,1,3)) 

brks<-seq(from=6, to=15, by=0.5)
hist((dat.linear.raw[,"totaltoelength"]), breaks=brks, border = "white", xaxt="n", yaxt="n", xlab=NA, ylab=NA, main=NA, ylim=c(0, 40))
abline(v=out$estimate[1], col="darkgrey", lwd=3)
abline(v=out$estimate[2], col="darkgreen", lwd=3)
hist(dat.linear.raw[dat.field$Habitat_Category=="forest","totaltoelength"], col="darkgreen", add=T)
hist((dat.linear.raw[dat.field$Habitat_Category=="urban","totaltoelength"]), col=grey.transparant, add=T)

mtext("Count", side=4, line=1.5, cex=1)

axis(side = 1, line = -0.15, at = c(6,8,10,12,14), padj = -1)
axis(side = 4, at = c(0, 20, 40), label=c("0", "20", "40"), padj = -1)

abline(h=0)

text(x=13, y=35, labels = paste("  t = ", signif(out$statistic, digits = 3)), cex = 0.6, pos=4 )
text(x=13, y=30, labels = paste("df = ", round(out$parameter, digits = 1)), cex = 0.6, pos=4 )
text(x=13, y=25, labels = paste(" p < 0.001"), cex = 0.6, pos=4, font = 2)

dev.off()



#Second ask if the ratio of pad length / total toe length has changed in urban lizards 
pad_total_ratio<-dat.linear.raw[,"padlength"]/dat.linear.raw[,"totaltoelength"]

out<-t.test(log(pad_total_ratio[dat.field$Habitat_Category=="urban"]), log(pad_total_ratio[dat.field$Habitat_Category=="forest"]))
out #yes, the means are signifincalty different p-value = 7.09e-08
out$statistic #t value 5.565084
out$parameter #df 236.1203
out$p.value  # 7.090081e-08

exp(out$estimate[1]) #0.337643 urban
exp(out$estimate[2]) #0.3235786 forest

#get 95% confidence intervals 
CI<-t.test(log(pad_total_ratio[dat.field$Habitat_Category=="forest"]), conf.level = 0.95)$conf.int[1:2]
exp(CI) #between 0.3200037 and 0.3271935

CI<-t.test(log(pad_total_ratio[dat.field$Habitat_Category=="urban"]), conf.level = 0.95)$conf.int[1:2]
exp(CI) #between 0.3341890 and 0.3411327


#pad coverage between forest and urban
(0.337643-0.3235786)*100



#Plots
#histogram comparison of pad length / total toe length
pdf(file=file.path("Output/Plots/Linear/Toe PadLength-TotalLength Hist.pdf"), width=4, height=4)
par(mar=c(0,3.5,0,1), pty="s") 

brks<-seq(from=0.26, to=0.40, by=0.02)
hist(pad_total_ratio, breaks=brks, border = "white", xaxt="n", xlab=NA, ylab=NA, main=NA, ylim=c(0, 30), xlim=c(0.25, 0.4))
abline(v=exp(out$estimate[1]), col="darkgrey", lwd=3)
abline(v=exp(out$estimate[2]), col="darkgreen", lwd=3)
hist(pad_total_ratio[dat.field$Habitat_Category=="forest"], col="darkgreen", add=T)
hist((pad_total_ratio[dat.field$Habitat_Category=="urban"]), col=grey.transparant, add=T)

mtext("Ratio of Pad Length/Total Toe Length", side=1, line=1, cex=1.3, adj = 1)
mtext("Count", side=2, line=2, cex=1.5)

axis(side = 1, line = -0.6, at = c(0.25,0.3,0.35,0.40), padj = -1)
abline(h=0)

text(x=0.24, y=30, labels = paste("  t = ", signif(out$statistic, digits = 3)), cex = 0.6, pos=4 )
text(x=0.24, y=28.5, labels = paste("df = ", round(out$parameter, digits = 1)), cex = 0.6, pos=4 )
text(x=0.24, y=27, labels = paste(" p < 0.001"), cex = 0.6, pos=4, font = 2)

dev.off()

# pad length vs total toe length scatter plot
green.transparant<-"#00800080" #transparnt green
grey.transparant<-"#BEBEBE80" #transparant grey

HabColors<-as.character(dat.field$Habitat_Category)
HabColors[HabColors=="urban"]<-grey.transparant
HabColors[HabColors=="forest"]<-green.transparant


pdf(file=file.path("Output/Plots/Linear/Toe PadLength-TotalLength Scatter.pdf"), width=4, height=4)
par(mar=c(2.5,3.5,0,1), pty="s") 

plot(dat.linear.raw[,"totaltoelength"], dat.linear.raw[,"padlength"], col="white", pch=19, xlab=NA, ylab=NA, asp=1, xlim=c(6.5,14))
abline(lm(dat.linear.raw[dat.field$Habitat_Category=="forest","padlength"]~0+dat.linear.raw[dat.field$Habitat_Category=="forest","totaltoelength"]), col=green.transparant, lwd=3)
abline(lm(dat.linear.raw[dat.field$Habitat_Category=="urban","padlength"]~0+dat.linear.raw[dat.field$Habitat_Category=="urban","totaltoelength"]), col=grey.transparant, lwd=3)

hpts<-chull(dat.linear.raw[dat.field$Habitat_Category=="forest","totaltoelength"], dat.linear.raw[dat.field$Habitat_Category=="forest","padlength"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(dat.linear.raw[dat.field$Habitat_Category=="forest","totaltoelength"][hpts], dat.linear.raw[dat.field$Habitat_Category=="forest","padlength"][hpts], col=green.transparant) #plot the lines

hpts<-chull(dat.linear.raw[dat.field$Habitat_Category=="urban","totaltoelength"], dat.linear.raw[dat.field$Habitat_Category=="urban","padlength"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(dat.linear.raw[dat.field$Habitat_Category=="urban","totaltoelength"][hpts], dat.linear.raw[dat.field$Habitat_Category=="urban","padlength"][hpts], col=grey.transparant) #plot the lines

points(dat.linear.raw[,"totaltoelength"], dat.linear.raw[,"padlength"], col=HabColors, pch=19)

#Muni urban and forest averages 
pt1<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Aguadilla", "totaltoelength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Aguadilla", "padlength"]))
pt2<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Aguadilla", "totaltoelength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Aguadilla", "padlength"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="grey", col="black", pch=24)
points(pt2[1], pt2[2], bg="darkgreen", col="black", pch=24)

pt1<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Arecibo", "totaltoelength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Arecibo", "padlength"]))
pt2<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Arecibo", "totaltoelength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Arecibo", "padlength"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="grey", col="black", pch=23)
points(pt2[1], pt2[2], bg="darkgreen", col="black", pch=23)

pt1<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Mayaguez", "totaltoelength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Mayaguez", "padlength"]))
pt2<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Mayaguez", "totaltoelength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Mayaguez", "padlength"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="grey", col="black", pch=21)
points(pt2[1], pt2[2], bg="darkgreen", col="black", pch=21)

pt1<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Ponce", "totaltoelength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Ponce", "padlength"]))
pt2<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Ponce", "totaltoelength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Ponce", "padlength"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="grey", col="black", pch=22)
points(pt2[1], pt2[2], bg="darkgreen", col="black", pch=22)

pt1<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "San Juan", "totaltoelength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "San Juan", "padlength"]))
pt2<-c(mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "San Juan", "totaltoelength"]), mean(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "San Juan", "padlength"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="grey", col="black", pch=25)
points(pt2[1], pt2[2], bg="darkgreen", col="black", pch=25)


mtext("Total Toe Length (mm)", side=1, line=2.4, cex=1.5)
mtext("Pad Length (mm)", side=2, line=2, cex=1.5)


legend(x=11.6, y=7.7, pch=c(24,23,21,22,25), legend=rep("", 5), pt.bg="darkgreen", bty="n", cex=0.8)
legend(x=12, y=7.7, pch=c(24,23,21,22,25), pt.bg="grey", legend=c("Aguadilla", "Arecibo", "Mayaguez", "Ponce", "San Juan"), bty="n", cex=0.8)
text(12.2, 7.7, "Forest", cex=0.8, pos=2, xpd=T)
text(13.3, 7.7, "Urban", cex=0.8, pos=2, xpd=T)


dev.off()



#given these results, we can also ask if urban lizards also have longer proximal toe segments 
out<-t.test(log(dat.linear.raw[dat.field$Habitat_Category=="urban","proxtoelength"]), log(dat.linear.raw[dat.field$Habitat_Category=="forest","proxtoelength"]))
out #yes, the means are signifincalty different p-value = 3.389e-05
out$statistic #t value 4.23457
out$parameter #df 215.832
out$p.value  #3.389339e-05

exp(out$estimate[1]) #7.007748 urban
exp(out$estimate[2]) #6.625065 forest

#get 95% confidence intervals 
CI<-t.test(log(dat.linear.raw[dat.field$Habitat_Category=="forest","proxtoelength"]), conf.level = 0.95)$conf.int[1:2]
exp(CI) #between 6.488681 and 6.764317

CI<-t.test(log(dat.linear.raw[dat.field$Habitat_Category=="urban","proxtoelength"]), conf.level = 0.95)$conf.int[1:2]
exp(CI) #between 6.896294 and 7.121004



#histogram comparison of proximal toe segment length
pdf(file=file.path("Output/Plots/Linear/Toe Prox Toe Length Hist.pdf"), width=4, height=4)
par(mar=c(0,3.5,0,1), pty="s") 

brks<-seq(from=4, to=10, by=0.5)
hist((dat.linear.raw[,"proxtoelength"]), breaks=brks, border = "white", xaxt="n", xlab=NA, ylab=NA, main=NA, ylim=c(0, 41))
abline(v=exp(out$estimate[1]), col="darkgrey", lwd=3)
abline(v=exp(out$estimate[2]), col="darkgreen", lwd=3)
hist(dat.linear.raw[dat.field$Habitat_Category=="forest","proxtoelength"], col="darkgreen", add=T)
hist((dat.linear.raw[dat.field$Habitat_Category=="urban","proxtoelength"]), col=grey.transparant, add=T)

mtext("Proximal Toe Segment Length (mm)", side=1, line=1, cex=1.3, adj = 1)
mtext("Count", side=2, line=2, cex=1.5)

axis(side = 1, line = -0.6, at = c(4,6,8,10), padj = -1)
abline(h=0)

text(x=3.8, y=40, labels = paste("  t = ", signif(out$statistic, digits = 3)), cex = 0.6, pos=4 )
text(x=3.8, y=38.5, labels = paste("df = ", round(out$parameter, digits = 1)), cex = 0.6, pos=4 )
text(x=3.8, y=37, labels = paste(" p < 0.001"), cex = 0.6, pos=4, font = 2)

dev.off()



#For each Municipality, make its own pad length vs total length scatter plot, with lines through the origin to show its expected isometric change (forest line) vs its urban ratio, with forest and urban means and segments 

pdf(file=file.path("Output/Plots/Linear/Toe PadLength-TotalLength Scatter_Municipality_sep.pdf"), width=10, height=3)
par(mfrow=c(1,5), mar=c(4,4,2,0.5), pty="s")


#Aguadilla
forest.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Aguadilla", "totaltoelength"], dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Aguadilla", "padlength"])
urban.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Aguadilla", "totaltoelength"], dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Aguadilla", "padlength"])

plot(dat.linear.raw[,"totaltoelength"], dat.linear.raw[,"padlength"], col="white", pch=19, xlab=NA, ylab=NA, asp=1, xaxt="n")
abline(lm(forest.pts[,2]~0+forest.pts[,1]), col=green.transparant, lwd=3)
abline(lm(urban.pts[,2]~0+urban.pts[,1]), col=grey.transparant, lwd=3)

axis(side=1, at=c(8, 9,10, 11,12, 13), labels = c("8", NA, "10", NA, "12", NA))

hpts<-chull(forest.pts[,2], forest.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[hpts,1], forest.pts[hpts,2], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[,2], urban.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[hpts,1], urban.pts[hpts,2], col=grey.transparant) #plot the lines

points(forest.pts, bg=green.transparant, col=NA, pch=24, cex=1.2)
points(urban.pts, bg=grey.transparant, col=NA, pch=24, cex=1.2)

#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,1]), mean(forest.pts[,2]))
pt2<-c(mean(urban.pts[,1]), mean(urban.pts[,2]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=24)
points(pt2[1], pt2[2], bg="gray", col="black", pch=24)

mtext("Total Toe Length (mm)", side=1, line=2.4, cex=1)
mtext("Pad Length (mm)", side=2, line=2, cex=1)
mtext("Aguadilla", side=3, line=0.5, font=2, cex=1)


#Arecibo
forest.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Arecibo", "totaltoelength"], dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Arecibo", "padlength"])
urban.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Arecibo", "totaltoelength"], dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Arecibo", "padlength"])

plot(dat.linear.raw[,"totaltoelength"], dat.linear.raw[,"padlength"], col="white", pch=19, xlab=NA, ylab=NA, asp=1, xaxt="n")
abline(lm(forest.pts[,2]~0+forest.pts[,1]), col=green.transparant, lwd=3)
abline(lm(urban.pts[,2]~0+urban.pts[,1]), col=grey.transparant, lwd=3)

axis(side=1, at=c(8, 9,10, 11,12, 13), labels = c("8", NA, "10", NA, "12", NA))

hpts<-chull(forest.pts[,2], forest.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[hpts,1], forest.pts[hpts,2], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[,2], urban.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[hpts,1], urban.pts[hpts,2], col=grey.transparant) #plot the lines

points(forest.pts, bg=green.transparant, col=NA, pch=23, cex=1.2)
points(urban.pts, bg=grey.transparant, col=NA, pch=23, cex=1.2)

#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,1]), mean(forest.pts[,2]))
pt2<-c(mean(urban.pts[,1]), mean(urban.pts[,2]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=23)
points(pt2[1], pt2[2], bg="gray", col="black", pch=23)

mtext("Total Toe Length (mm)", side=1, line=2.4, cex=1)
mtext("Pad Length (mm)", side=2, line=2, cex=1)
mtext("Arecibo", side=3, line=0.5, font=2, cex=1)


#Mayaguez
forest.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Mayaguez", "totaltoelength"], dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Mayaguez", "padlength"])
urban.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Mayaguez", "totaltoelength"], dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Mayaguez", "padlength"])

plot(dat.linear.raw[,"totaltoelength"], dat.linear.raw[,"padlength"], col="white", pch=19, xlab=NA, ylab=NA, asp=1, xaxt="n")
abline(lm(forest.pts[,2]~0+forest.pts[,1]), col=green.transparant, lwd=3)
abline(lm(urban.pts[,2]~0+urban.pts[,1]), col=grey.transparant, lwd=3)

axis(side=1, at=c(8, 9,10, 11,12, 13), labels = c("8", NA, "10", NA, "12", NA))

hpts<-chull(forest.pts[,2], forest.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[hpts,1], forest.pts[hpts,2], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[,2], urban.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[hpts,1], urban.pts[hpts,2], col=grey.transparant) #plot the lines

points(forest.pts, bg=green.transparant, col=NA, pch=21, cex=1.2)
points(urban.pts, bg=grey.transparant, col=NA, pch=21, cex=1.2)

#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,1]), mean(forest.pts[,2]))
pt2<-c(mean(urban.pts[,1]), mean(urban.pts[,2]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=21)
points(pt2[1], pt2[2], bg="gray", col="black", pch=21)

mtext("Total Toe Length (mm)", side=1, line=2.4, cex=1)
mtext("Pad Length (mm)", side=2, line=2, cex=1)
mtext("Mayaguez", side=3, line=0.5, font=2, cex=1)



#Ponce
forest.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Ponce", "totaltoelength"], dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Ponce", "padlength"])
urban.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Ponce", "totaltoelength"], dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Ponce", "padlength"])

plot(dat.linear.raw[,"totaltoelength"], dat.linear.raw[,"padlength"], col="white", pch=19, xlab=NA, ylab=NA, asp=1, xaxt="n")
abline(lm(forest.pts[,2]~0+forest.pts[,1]), col=green.transparant, lwd=3)
abline(lm(urban.pts[,2]~0+urban.pts[,1]), col=grey.transparant, lwd=3)

axis(side=1, at=c(8, 9,10, 11,12, 13), labels = c("8", NA, "10", NA, "12", NA))

hpts<-chull(forest.pts[,2], forest.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[hpts,1], forest.pts[hpts,2], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[,2], urban.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[hpts,1], urban.pts[hpts,2], col=grey.transparant) #plot the lines

points(forest.pts, bg=green.transparant, col=NA, pch=22, cex=1.2)
points(urban.pts, bg=grey.transparant, col=NA, pch=22, cex=1.2)

#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,1]), mean(forest.pts[,2]))
pt2<-c(mean(urban.pts[,1]), mean(urban.pts[,2]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=22)
points(pt2[1], pt2[2], bg="gray", col="black", pch=22)

mtext("Total Toe Length (mm)", side=1, line=2.4, cex=1)
mtext("Pad Length (mm)", side=2, line=2, cex=1)
mtext("Ponce", side=3, line=0.5, font=2, cex=1)



#San Juan
forest.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "San Juan", "totaltoelength"], dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "San Juan", "padlength"])
urban.pts<-cbind(dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "San Juan", "totaltoelength"], dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "San Juan", "padlength"])

plot(dat.linear.raw[,"totaltoelength"], dat.linear.raw[,"padlength"], col="white", pch=19, xlab=NA, ylab=NA, asp=1, xaxt="n")
abline(lm(forest.pts[,2]~0+forest.pts[,1]), col=green.transparant, lwd=3)
abline(lm(urban.pts[,2]~0+urban.pts[,1]), col=grey.transparant, lwd=3)

axis(side=1, at=c(8, 9,10, 11,12, 13), labels = c("8", NA, "10", NA, "12", NA))

hpts<-chull(forest.pts[,2], forest.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[hpts,1], forest.pts[hpts,2], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[,2], urban.pts[,1]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[hpts,1], urban.pts[hpts,2], col=grey.transparant) #plot the lines

points(forest.pts, bg=green.transparant, col=NA, pch=25, cex=1.2)
points(urban.pts, bg=grey.transparant, col=NA, pch=25, cex=1.2)

#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,1]), mean(forest.pts[,2]))
pt2<-c(mean(urban.pts[,1]), mean(urban.pts[,2]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=25)
points(pt2[1], pt2[2], bg="gray", col="black", pch=25)

mtext("Total Toe Length (mm)", side=1, line=2.4, cex=1)
mtext("Pad Length (mm)", side=2, line=2, cex=1)
mtext("San Juan", side=3, line=0.5, font=2, cex=1)


dev.off()



#remove variables we no logner need 
rm(forest.pts)
rm(urban.pts)
rm(out)
rm(brks)
rm(hpts)
rm(pt1)
rm(pt2)
rm(pad_total_ratio)
rm(CI)



###### Linear Lamellae Proportions Stats and Plots ####

#ask how toe pad area, the number of lamellae, and lamellae width are related to each other and to habitat category. 

#First ask if toe pad area is different in urban and forest lizards 
out<-t.test(log(dat.field[dat.field$Habitat_Category=="urban","Area_mm2"]), log(dat.field[dat.field$Habitat_Category=="forest","Area_mm2"]))
out #yes, the means are signifincalty different p-value = 1.972e-09
out$statistic #t value 6.256625
out$parameter #df 224.2708
out$p.value  #1.971543e-09

exp(out$estimate[1]) #6.865191 urban
exp(out$estimate[2]) #5.570076 forest

#get 95% confidence intervals 

CI<-t.test(log(dat.field[dat.field$Habitat_Category=="forest","Area_mm2"]), conf.level = 0.95)$conf.int[1:2]
exp(CI) #between 5.292873 and 5.861797

CI<-t.test(log(dat.field[dat.field$Habitat_Category=="urban","Area_mm2"]), conf.level = 0.95)$conf.int[1:2]
exp(CI) #between 6.582187 and 7.160362


#histogram plot comparison of toe pad area  (will be add to axis of scatter plot)
pdf(file=file.path("Output/Plots/Linear/Pad Area Hist.pdf"), width=4, height=1.5)
par(mar=c(2.5,1,1,3)) 

brks<-seq(from=2, to=12, by=0.5)
hist((dat.field[,"Area_mm2"]), breaks=brks, border = "white", xaxt="n", yaxt="n", xlab=NA, ylab=NA, main=NA, ylim=c(0, 25))
abline(v=exp(out$estimate[1]), col="darkgrey", lwd=3)
abline(v=exp(out$estimate[2]), col="darkgreen", lwd=3)
hist(dat.field[dat.field$Habitat_Category=="forest","Area_mm2"], breaks=brks, col="darkgreen", add=T)
hist((dat.field[dat.field$Habitat_Category=="urban","Area_mm2"]), breaks=brks, col=grey.transparant, add=T)

mtext("Count", side=4, line=1.5, cex=1)

axis(side = 1, at = c(2, 4, 6, 8, 10, 12), padj = -1)
axis(side = 4, at = c(0, 10, 20), label=c("0", NA, "20"), padj = -1)

text(x=10, y=20, labels = paste("  t = ", signif(out$statistic, digits = 3)), cex = 0.6, pos=4 )
text(x=10, y=16, labels = paste("df = ", round(out$parameter, digits = 1)), cex = 0.6, pos=4 )
text(x=10, y=12, labels = paste(" p < 0.001"), cex = 0.6, pos=4, font = 2)

dev.off()



#Then ask if lamellae width is different in urban and forest lizards 
out<-t.test(log(dat.linear.raw[dat.field$Habitat_Category=="urban","avelamwidth"]), log(dat.linear.raw[dat.field$Habitat_Category=="forest","avelamwidth"]))
out #yes, the means are signifincalty different p-value = 7.275e-07
out$statistic #t value 5.091671
out$parameter #df 235.077
out$p.value  #7.27502e-07

exp(out$estimate[1]) #0.1671097 urban
exp(out$estimate[2]) #0.1461837 forest

#get 95% confidence intervals 
CI<-t.test(log(dat.linear.raw[dat.field$Habitat_Category=="forest","avelamwidth"]), conf.level = 0.95)$conf.int[1:2]
exp(CI) #between 0.1406773 and 0.1519057

CI<-t.test(log(dat.linear.raw[dat.field$Habitat_Category=="urban","avelamwidth"]), conf.level = 0.95)$conf.int[1:2]
exp(CI) #between 0.1613448 and 0.1730806


#histogram plot comparison of lamellae width
pdf(file=file.path("Output/Plots/Linear/Pad LamWidth Hist.pdf"), width=4, height=1.5)
par(mar=c(2.5,1,1,3)) 

brks<-seq(from=0.08, to=0.3, by=0.01)
hist((dat.linear.raw[,"avelamwidth"]), breaks=brks, border = "white", xaxt="n", yaxt="n", xlab=NA, ylab=NA, main=NA, ylim=c(0, 25))
abline(v=exp(out$estimate[1]), col="darkgrey", lwd=3)
abline(v=exp(out$estimate[2]), col="darkgreen", lwd=3)
hist(dat.linear.raw[dat.field$Habitat_Category=="forest","avelamwidth"], breaks=brks, col="darkgreen", add=T)
hist((dat.linear.raw[dat.field$Habitat_Category=="urban","avelamwidth"]), breaks=brks, col=grey.transparant, add=T)

axis(side = 1,  at = c(0.1, 0.14, 0.18, 0.22, 0.26, 0.3), padj = -1)
axis(side = 4, at = c(0, 10, 20), label=c("0", NA, "20"), padj = -1)
mtext("Count", side=4, line=2, cex=1)

text(x=0.26, y=20, labels = paste("  t = ", signif(out$statistic, digits = 3)), cex = 0.6, pos=4 )
text(x=0.26, y=16, labels = paste("df = ", round(out$parameter, digits = 1)), cex = 0.6, pos=4 )
text(x=0.26, y=12, labels = paste(" p < 0.001"), cex = 0.6, pos=4, font = 2)

dev.off()




#Lastly ask if the number of lamellae is different in urban and forest lizards 
out<-t.test(sqrt(dat.field[dat.field$Habitat_Category=="urban","Lamellae_Count"]), sqrt(dat.field[dat.field$Habitat_Category=="forest","Lamellae_Count"]))
out #yes, the means are signifincalty different p-value = 0.001109
out$statistic #t value 3.303425
out$parameter #df 228.4394
out$p.value  #0.001108615

(out$estimate[1])^2 #22.44374 urban
(out$estimate[2])^2 #21.86948 forest

#get 95% confidence intervals 
CI<-t.test(sqrt(dat.field[dat.field$Habitat_Category=="forest","Lamellae_Count"]), conf.level = 0.95)$conf.int[1:2]
(CI)^2 #between 21.61036 and 22.13015

CI<-t.test(sqrt(dat.field[dat.field$Habitat_Category=="urban","Lamellae_Count"]), conf.level = 0.95)$conf.int[1:2]
(CI)^2 #between 22.21912 and 22.66949



#histogram plot comparison of lamellae count  
pdf(file=file.path("Output/Plots/Linear/Pad LamCount.pdf"), width=4, height=1.5)
par(mar=c(2.5,1,1,3)) 

brks<-seq(from=18, to=27, by=1)
hist((dat.field[,"Lamellae_Count"]), breaks=brks, border = "white", xaxt="n", yaxt="n", xlab=NA, ylab=NA, main=NA, ylim=c(0, 45))
abline(v=(out$estimate[1])^2, col="darkgrey", lwd=3)
abline(v=(out$estimate[2])^2, col="darkgreen", lwd=3)
hist(dat.field[dat.field$Habitat_Category=="forest","Lamellae_Count"], breaks=brks, col="darkgreen", add=T)
hist((dat.field[dat.field$Habitat_Category=="urban","Lamellae_Count"]), breaks=brks, col=grey.transparant, add=T)

axis(side = 1, at = seq(from=18, to=27, by=1), padj = -1)
axis(side = 4, at = c(0, 20, 40), label=c("0", NA, "40"), padj = -1)
mtext("Count", side=4, line=2, cex=1)


text(x=24.5, y=40, labels = paste("  t = ", signif(out$statistic, digits = 3)), cex = 0.6, pos=4 )
text(x=24.5, y=32, labels = paste("df = ", round(out$parameter, digits = 1)), cex = 0.6, pos=4 )
text(x=24.5, y=24, labels = paste(" p = ", round(out$p.value, digits = 3)), cex = 0.6, pos=4, font = 2)

dev.off()



#explore correlations between area, lamellae width, and lamellae count
library(car)

#how is area correlated with lam width and/or lamellae count
out<-Anova(glm(log(dat.field[,"Area_mm2"])~log(dat.linear.raw[,"avelamwidth"])*sqrt(dat.field[,"Lamellae_Count"])),  type="II")
out$`Pr(>Chisq)`[1] #lam width pval  7.063535e-30
out$`Pr(>Chisq)`[2] #lam count pval  6.608312e-10
out$`Pr(>Chisq)`[3] #interaction pval  0.6515202
#Both lam width and lamellae count are significantly correlate with area, but the interaction is not

#Are width and count correlated with each other?
Anova(glm(log(dat.linear.raw[,"avelamwidth"])~sqrt(dat.field[,"Lamellae_Count"])))
Anova(glm(log(dat.linear.raw[,"avelamwidth"])~sqrt(dat.field[,"Lamellae_Count"])))$`Pr(>Chisq)` #pval
#intersetingly no, they are not correlated with each other  p = 0.2234717



#large summary plots

pdf(file=file.path("Output/Plots/Linear/Pad AreaLamCount Scatter.pdf"), width=4, height=8.3)
par(mfrow=c(2,1),mar=c(3,3.5,1,1), pty="s") 


plot(dat.field[,"Area_mm2"], dat.field[,"Lamellae_Count"], col="white", xlab=NA, ylab=NA, xaxt="n", yaxt="n", ylim=c(16, 27), xlim=c(-1,12))
abline(lm(dat.field[dat.field$Habitat_Category=="forest","Lamellae_Count"]~dat.field[dat.field$Habitat_Category=="forest","Area_mm2"]), col=green.transparant, lwd=3)
abline(lm(dat.field[dat.field$Habitat_Category=="urban","Lamellae_Count"]~dat.field[dat.field$Habitat_Category=="urban","Area_mm2"]), col=grey.transparant, lwd=3)

hpts<-chull(dat.field[dat.field$Habitat_Category=="forest","Area_mm2"], dat.field[dat.field$Habitat_Category=="forest","Lamellae_Count"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(dat.field[dat.field$Habitat_Category=="forest","Area_mm2"][hpts], dat.field[dat.field$Habitat_Category=="forest","Lamellae_Count"][hpts], col=green.transparant) #plot the lines

hpts<-chull(dat.field[dat.field$Habitat_Category=="urban","Area_mm2"], dat.field[dat.field$Habitat_Category=="urban","Lamellae_Count"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(dat.field[dat.field$Habitat_Category=="urban","Area_mm2"][hpts], dat.field[dat.field$Habitat_Category=="urban","Lamellae_Count"][hpts], col=grey.transparant) #plot the lines

points(dat.field[,"Area_mm2"], dat.field[,"Lamellae_Count"], col=HabColors, pch=19)

axis(side = 1, at = c(0,1,2,3,4,5,6,7,8,9,10,11,12), labels = c("0",NA,"2",NA,"4",NA,"6",NA,"8",NA,"10",NA,"12"), padj = -0.8)
axis(side = 2, at = c(seq(16,27,by=1)), labels = c("16",NA,"18",NA,"20",NA,"22",NA,"24",NA,"26",NA))

mtext(expression(paste("Toepad Area (mm"^"2",")")), side=1, line=2.2, cex=1.5)
mtext("Lamellae Count", side=2, line=2, cex=1.5)



plot(dat.field[,"Area_mm2"], dat.linear.raw[,"avelamwidth"], col="white", xlab=NA, ylab=NA, xaxt="n", ylim=c(0, 0.33), xlim=c(-1,12))
abline(lm(dat.linear.raw[dat.field$Habitat_Category=="forest","avelamwidth"]~dat.field[dat.field$Habitat_Category=="forest","Area_mm2"]), col=green.transparant, lwd=3)
abline(lm(dat.linear.raw[dat.field$Habitat_Category=="urban","avelamwidth"]~dat.field[dat.field$Habitat_Category=="urban","Area_mm2"]), col=grey.transparant, lwd=3)

hpts<-chull(dat.field[dat.field$Habitat_Category=="forest","Area_mm2"], dat.linear.raw[dat.field$Habitat_Category=="forest","avelamwidth"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(dat.field[dat.field$Habitat_Category=="forest","Area_mm2"][hpts], dat.linear.raw[dat.field$Habitat_Category=="forest","avelamwidth"][hpts], col=green.transparant) #plot the lines

hpts<-chull(dat.field[dat.field$Habitat_Category=="urban","Area_mm2"], dat.linear.raw[dat.field$Habitat_Category=="urban","avelamwidth"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(dat.field[dat.field$Habitat_Category=="urban","Area_mm2"][hpts], dat.linear.raw[dat.field$Habitat_Category=="urban","avelamwidth"][hpts], col=grey.transparant) #plot the lines

points(dat.field[,"Area_mm2"], dat.linear.raw[,"avelamwidth"], col=HabColors, pch=19)

axis(side = 1, at = c(0,1,2,3,4,5,6,7,8,9,10,11,12), labels = c("0",NA,"2",NA,"4",NA,"6",NA,"8",NA,"10",NA,"12"), padj = -0.8)

mtext(expression(paste("Toepad Area (mm"^"2",")")), side=1, line=2.2, cex=1.5)
mtext("Average Lamellae Height (mm)", side=2, line=2, cex=1.5)


dev.off()


#For each Municipality, we made individual pad area vs lamellae count and pad area vs lamellae width scatter plots with lines not forced through the origin and also with forest and urban means and segments 

pdf(file=file.path("Output/Plots/Linear/Pad AreaLamCount Scatter_Municipality_sep.pdf"), width=18, height=8.3)
par(mfcol=c(2,5), mar=c(4,5,2,0.5), pty="s")


#Aguadilla
forest.pts<-cbind(dat.field[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Aguadilla", "Area_mm2"], dat.field[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Aguadilla", "Lamellae_Count"], dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Aguadilla", "avelamwidth"])
colnames(forest.pts)<-c("Muni_area", "Muni_count", "Muni_width")
urban.pts<-cbind(dat.field[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Aguadilla", "Area_mm2"], dat.field[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Aguadilla", "Lamellae_Count"], dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Aguadilla", "avelamwidth"])
colnames(urban.pts)<-c("Muni_area", "Muni_count", "Muni_width")


plot(dat.field[,"Area_mm2"], dat.field[,"Lamellae_Count"], col="white", xlab=NA, ylab=NA, xaxt="n", ylim=c(18, 27), xlim=c(2,12), cex.axis=1.5)

hpts<-chull(forest.pts[, "Muni_area"], forest.pts[,"Muni_count"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[, "Muni_area"][hpts], forest.pts[,"Muni_count"][hpts], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[, "Muni_area"], urban.pts[,"Muni_count"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[, "Muni_area"][hpts], urban.pts[,"Muni_count"][hpts], col=grey.transparant) #plot the lines

points(x=forest.pts[,"Muni_area"], y=forest.pts[,"Muni_count"], bg=green.transparant, col=NA, pch=24, cex=1.2)
points(x=urban.pts[,"Muni_area"], y=urban.pts[,"Muni_count"], bg=grey.transparant, col=NA, pch=24, cex=1.2)

axis(side = 1, at = c(2,3,4,5,6,7,8,9,10,11,12), labels = c("2",NA,"4",NA,"6",NA,"8",NA,"10",NA,"12"), padj = 0, cex.axis=1.5)

mtext(expression(paste("Toepad Area (mm"^"2",")")), side=1, line=3.5, cex=1.5)
mtext("Lamellae Count", side=2, line=3, cex=1.5)


#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,"Muni_area"]), mean(forest.pts[,"Muni_count"]))
pt2<-c(mean(urban.pts[,"Muni_area"]), mean(urban.pts[,"Muni_count"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=24)
points(pt2[1], pt2[2], bg="gray", col="black", pch=24)

mtext("Aguadilla", side=3, line=0.5, font=2, cex=1.5)




plot(dat.field[,"Area_mm2"], dat.linear.raw[,"avelamwidth"], col="white", xlab=NA, ylab=NA, xaxt="n", ylim=c(0.05, 0.33), xlim=c(2,12), cex.axis=1.5)

hpts<-chull(forest.pts[, "Muni_area"], forest.pts[,"Muni_width"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[, "Muni_area"][hpts], forest.pts[,"Muni_width"][hpts], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[, "Muni_area"], urban.pts[,"Muni_width"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[, "Muni_area"][hpts], urban.pts[,"Muni_width"][hpts], col=grey.transparant) #plot the lines

points(x=forest.pts[,"Muni_area"], y=forest.pts[,"Muni_width"], bg=green.transparant, col=NA, pch=24, cex=1.2)
points(x=urban.pts[,"Muni_area"], y=urban.pts[,"Muni_width"], bg=grey.transparant, col=NA, pch=24, cex=1.2)

axis(side = 1, at = c(2,3,4,5,6,7,8,9,10,11,12), labels = c("2",NA,"4",NA,"6",NA,"8",NA,"10",NA,"12"), padj = 0, cex.axis=1.5)

mtext(expression(paste("Toepad Area (mm"^"2",")")), side=1, line=3.5, cex=1.5)
mtext("Average Lamellae Height (mm)", side=2, line=3, cex=1.5)

#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,"Muni_area"]), mean(forest.pts[,"Muni_width"]))
pt2<-c(mean(urban.pts[,"Muni_area"]), mean(urban.pts[,"Muni_width"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=24)
points(pt2[1], pt2[2], bg="gray", col="black", pch=24)



#Arecibo
forest.pts<-cbind(dat.field[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Arecibo", "Area_mm2"], dat.field[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Arecibo", "Lamellae_Count"], dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Arecibo", "avelamwidth"])
colnames(forest.pts)<-c("Muni_area", "Muni_count", "Muni_width")
urban.pts<-cbind(dat.field[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Arecibo", "Area_mm2"], dat.field[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Arecibo", "Lamellae_Count"], dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Arecibo", "avelamwidth"])
colnames(urban.pts)<-c("Muni_area", "Muni_count", "Muni_width")


plot(dat.field[,"Area_mm2"], dat.field[,"Lamellae_Count"], col="white", xlab=NA, ylab=NA, xaxt="n", ylim=c(18, 27), xlim=c(2,12), cex.axis=1.5)

hpts<-chull(forest.pts[, "Muni_area"], forest.pts[,"Muni_count"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[, "Muni_area"][hpts], forest.pts[,"Muni_count"][hpts], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[, "Muni_area"], urban.pts[,"Muni_count"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[, "Muni_area"][hpts], urban.pts[,"Muni_count"][hpts], col=grey.transparant) #plot the lines

points(x=forest.pts[,"Muni_area"], y=forest.pts[,"Muni_count"], bg=green.transparant, col=NA, pch=23, cex=1.2)
points(x=urban.pts[,"Muni_area"], y=urban.pts[,"Muni_count"], bg=grey.transparant, col=NA, pch=23, cex=1.2)

axis(side = 1, at = c(2,3,4,5,6,7,8,9,10,11,12), labels = c("2",NA,"4",NA,"6",NA,"8",NA,"10",NA,"12"), padj = 0, cex.axis=1.5)

mtext(expression(paste("Toepad Area (mm"^"2",")")), side=1, line=3.5, cex=1.5)
mtext("Lamellae Count", side=2, line=3, cex=1.5)


#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,"Muni_area"]), mean(forest.pts[,"Muni_count"]))
pt2<-c(mean(urban.pts[,"Muni_area"]), mean(urban.pts[,"Muni_count"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=23)
points(pt2[1], pt2[2], bg="gray", col="black", pch=23)

mtext("Arecibo", side=3, line=0.5, font=2, cex=1.5)




plot(dat.field[,"Area_mm2"], dat.linear.raw[,"avelamwidth"], col="white", xlab=NA, ylab=NA, xaxt="n", ylim=c(0.05, 0.33), xlim=c(2,12), cex.axis=1.5)

hpts<-chull(forest.pts[, "Muni_area"], forest.pts[,"Muni_width"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[, "Muni_area"][hpts], forest.pts[,"Muni_width"][hpts], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[, "Muni_area"], urban.pts[,"Muni_width"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[, "Muni_area"][hpts], urban.pts[,"Muni_width"][hpts], col=grey.transparant) #plot the lines

points(x=forest.pts[,"Muni_area"], y=forest.pts[,"Muni_width"], bg=green.transparant, col=NA, pch=23, cex=1.2)
points(x=urban.pts[,"Muni_area"], y=urban.pts[,"Muni_width"], bg=grey.transparant, col=NA, pch=23, cex=1.2)

axis(side = 1, at = c(2,3,4,5,6,7,8,9,10,11,12), labels = c("2",NA,"4",NA,"6",NA,"8",NA,"10",NA,"12"), padj = 0, cex.axis=1.5)

mtext(expression(paste("Toepad Area (mm"^"2",")")), side=1, line=3.5, cex=1.5)
mtext("Average Lamellae Height (mm)", side=2, line=3, cex=1.5)

#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,"Muni_area"]), mean(forest.pts[,"Muni_width"]))
pt2<-c(mean(urban.pts[,"Muni_area"]), mean(urban.pts[,"Muni_width"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=23)
points(pt2[1], pt2[2], bg="gray", col="black", pch=23)




#Mayaguez
forest.pts<-cbind(dat.field[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Mayaguez", "Area_mm2"], dat.field[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Mayaguez", "Lamellae_Count"], dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Mayaguez", "avelamwidth"])
colnames(forest.pts)<-c("Muni_area", "Muni_count", "Muni_width")
urban.pts<-cbind(dat.field[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Mayaguez", "Area_mm2"], dat.field[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Mayaguez", "Lamellae_Count"], dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Mayaguez", "avelamwidth"])
colnames(urban.pts)<-c("Muni_area", "Muni_count", "Muni_width")


plot(dat.field[,"Area_mm2"], dat.field[,"Lamellae_Count"], col="white", xlab=NA, ylab=NA, xaxt="n", ylim=c(18, 27), xlim=c(2,12), cex.axis=1.5)

hpts<-chull(forest.pts[, "Muni_area"], forest.pts[,"Muni_count"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[, "Muni_area"][hpts], forest.pts[,"Muni_count"][hpts], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[, "Muni_area"], urban.pts[,"Muni_count"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[, "Muni_area"][hpts], urban.pts[,"Muni_count"][hpts], col=grey.transparant) #plot the lines

points(x=forest.pts[,"Muni_area"], y=forest.pts[,"Muni_count"], bg=green.transparant, col=NA, pch=21, cex=1.2)
points(x=urban.pts[,"Muni_area"], y=urban.pts[,"Muni_count"], bg=grey.transparant, col=NA, pch=21, cex=1.2)

axis(side = 1, at = c(2,3,4,5,6,7,8,9,10,11,12), labels = c("2",NA,"4",NA,"6",NA,"8",NA,"10",NA,"12"), padj = 0, cex.axis=1.5)

mtext(expression(paste("Toepad Area (mm"^"2",")")), side=1, line=3.5, cex=1.5)
mtext("Lamellae Count", side=2, line=3, cex=1.5)


#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,"Muni_area"]), mean(forest.pts[,"Muni_count"]))
pt2<-c(mean(urban.pts[,"Muni_area"]), mean(urban.pts[,"Muni_count"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=21)
points(pt2[1], pt2[2], bg="gray", col="black", pch=21)

mtext("Mayaguez", side=3, line=0.5, font=2, cex=1.5)




plot(dat.field[,"Area_mm2"], dat.linear.raw[,"avelamwidth"], col="white", xlab=NA, ylab=NA, xaxt="n", ylim=c(0.05, 0.33), xlim=c(2,12), cex.axis=1.5)

hpts<-chull(forest.pts[, "Muni_area"], forest.pts[,"Muni_width"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[, "Muni_area"][hpts], forest.pts[,"Muni_width"][hpts], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[, "Muni_area"], urban.pts[,"Muni_width"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[, "Muni_area"][hpts], urban.pts[,"Muni_width"][hpts], col=grey.transparant) #plot the lines

points(x=forest.pts[,"Muni_area"], y=forest.pts[,"Muni_width"], bg=green.transparant, col=NA, pch=21, cex=1.2)
points(x=urban.pts[,"Muni_area"], y=urban.pts[,"Muni_width"], bg=grey.transparant, col=NA, pch=21, cex=1.2)

axis(side = 1, at = c(2,3,4,5,6,7,8,9,10,11,12), labels = c("2",NA,"4",NA,"6",NA,"8",NA,"10",NA,"12"), padj = 0, cex.axis=1.5)

mtext(expression(paste("Toepad Area (mm"^"2",")")), side=1, line=3.5, cex=1.5)
mtext("Average Lamellae Height (mm)", side=2, line=3, cex=1.5)

#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,"Muni_area"]), mean(forest.pts[,"Muni_width"]))
pt2<-c(mean(urban.pts[,"Muni_area"]), mean(urban.pts[,"Muni_width"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=21)
points(pt2[1], pt2[2], bg="gray", col="black", pch=21)





#Ponce
forest.pts<-cbind(dat.field[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Ponce", "Area_mm2"], dat.field[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Ponce", "Lamellae_Count"], dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "Ponce", "avelamwidth"])
colnames(forest.pts)<-c("Muni_area", "Muni_count", "Muni_width")
urban.pts<-cbind(dat.field[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Ponce", "Area_mm2"], dat.field[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Ponce", "Lamellae_Count"], dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "Ponce", "avelamwidth"])
colnames(urban.pts)<-c("Muni_area", "Muni_count", "Muni_width")


plot(dat.field[,"Area_mm2"], dat.field[,"Lamellae_Count"], col="white", xlab=NA, ylab=NA, xaxt="n", ylim=c(18, 27), xlim=c(2,12), cex.axis=1.5)

hpts<-chull(forest.pts[, "Muni_area"], forest.pts[,"Muni_count"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[, "Muni_area"][hpts], forest.pts[,"Muni_count"][hpts], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[, "Muni_area"], urban.pts[,"Muni_count"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[, "Muni_area"][hpts], urban.pts[,"Muni_count"][hpts], col=grey.transparant) #plot the lines

points(x=forest.pts[,"Muni_area"], y=forest.pts[,"Muni_count"], bg=green.transparant, col=NA, pch=22, cex=1.2)
points(x=urban.pts[,"Muni_area"], y=urban.pts[,"Muni_count"], bg=grey.transparant, col=NA, pch=22, cex=1.2)

axis(side = 1, at = c(2,3,4,5,6,7,8,9,10,11,12), labels = c("2",NA,"4",NA,"6",NA,"8",NA,"10",NA,"12"), padj = 0, cex.axis=1.5)

mtext(expression(paste("Toepad Area (mm"^"2",")")), side=1, line=3.5, cex=1.5)
mtext("Lamellae Count", side=2, line=3, cex=1.5)


#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,"Muni_area"]), mean(forest.pts[,"Muni_count"]))
pt2<-c(mean(urban.pts[,"Muni_area"]), mean(urban.pts[,"Muni_count"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=22)
points(pt2[1], pt2[2], bg="gray", col="black", pch=22)

mtext("Ponce", side=3, line=0.5, font=2, cex=1.5)




plot(dat.field[,"Area_mm2"], dat.linear.raw[,"avelamwidth"], col="white", xlab=NA, ylab=NA, xaxt="n", ylim=c(0.05, 0.33), xlim=c(2,12), cex.axis=1.5)

hpts<-chull(forest.pts[, "Muni_area"], forest.pts[,"Muni_width"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[, "Muni_area"][hpts], forest.pts[,"Muni_width"][hpts], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[, "Muni_area"], urban.pts[,"Muni_width"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[, "Muni_area"][hpts], urban.pts[,"Muni_width"][hpts], col=grey.transparant) #plot the lines

points(x=forest.pts[,"Muni_area"], y=forest.pts[,"Muni_width"], bg=green.transparant, col=NA, pch=22, cex=1.2)
points(x=urban.pts[,"Muni_area"], y=urban.pts[,"Muni_width"], bg=grey.transparant, col=NA, pch=22, cex=1.2)

axis(side = 1, at = c(2,3,4,5,6,7,8,9,10,11,12), labels = c("2",NA,"4",NA,"6",NA,"8",NA,"10",NA,"12"), padj = 0, cex.axis=1.5)

mtext(expression(paste("Toepad Area (mm"^"2",")")), side=1, line=3.5, cex=1.5)
mtext("Average Lamellae Height (mm)", side=2, line=3, cex=1.5)

#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,"Muni_area"]), mean(forest.pts[,"Muni_width"]))
pt2<-c(mean(urban.pts[,"Muni_area"]), mean(urban.pts[,"Muni_width"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=22)
points(pt2[1], pt2[2], bg="gray", col="black", pch=22)




#San Juan
forest.pts<-cbind(dat.field[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "San Juan", "Area_mm2"], dat.field[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "San Juan", "Lamellae_Count"], dat.linear.raw[dat.field$Habitat_Category=="forest" & dat.field$Municipality == "San Juan", "avelamwidth"])
colnames(forest.pts)<-c("Muni_area", "Muni_count", "Muni_width")
urban.pts<-cbind(dat.field[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "San Juan", "Area_mm2"], dat.field[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "San Juan", "Lamellae_Count"], dat.linear.raw[dat.field$Habitat_Category=="urban" & dat.field$Municipality == "San Juan", "avelamwidth"])
colnames(urban.pts)<-c("Muni_area", "Muni_count", "Muni_width")


plot(dat.field[,"Area_mm2"], dat.field[,"Lamellae_Count"], col="white", xlab=NA, ylab=NA, xaxt="n", ylim=c(18, 27), xlim=c(2,12), cex.axis=1.5)

hpts<-chull(forest.pts[, "Muni_area"], forest.pts[,"Muni_count"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[, "Muni_area"][hpts], forest.pts[,"Muni_count"][hpts], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[, "Muni_area"], urban.pts[,"Muni_count"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[, "Muni_area"][hpts], urban.pts[,"Muni_count"][hpts], col=grey.transparant) #plot the lines

points(x=forest.pts[,"Muni_area"], y=forest.pts[,"Muni_count"], bg=green.transparant, col=NA, pch=25, cex=1.2)
points(x=urban.pts[,"Muni_area"], y=urban.pts[,"Muni_count"], bg=grey.transparant, col=NA, pch=25, cex=1.2)

axis(side = 1, at = c(2,3,4,5,6,7,8,9,10,11,12), labels = c("2",NA,"4",NA,"6",NA,"8",NA,"10",NA,"12"), padj = 0, cex.axis=1.5)

mtext(expression(paste("Toepad Area (mm"^"2",")")), side=1, line=3.5, cex=1.5)
mtext("Lamellae Count", side=2, line=3, cex=1.5)


#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,"Muni_area"]), mean(forest.pts[,"Muni_count"]))
pt2<-c(mean(urban.pts[,"Muni_area"]), mean(urban.pts[,"Muni_count"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=25)
points(pt2[1], pt2[2], bg="gray", col="black", pch=25)

mtext("San Juan", side=3, line=0.5, font=2, cex=1.5)




plot(dat.field[,"Area_mm2"], dat.linear.raw[,"avelamwidth"], col="white", xlab=NA, ylab=NA, xaxt="n", ylim=c(0.05, 0.33), xlim=c(2,12), cex.axis=1.5)

hpts<-chull(forest.pts[, "Muni_area"], forest.pts[,"Muni_width"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(forest.pts[, "Muni_area"][hpts], forest.pts[,"Muni_width"][hpts], col=green.transparant) #plot the lines

hpts<-chull(urban.pts[, "Muni_area"], urban.pts[,"Muni_width"]) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(urban.pts[, "Muni_area"][hpts], urban.pts[,"Muni_width"][hpts], col=grey.transparant) #plot the lines

points(x=forest.pts[,"Muni_area"], y=forest.pts[,"Muni_width"], bg=green.transparant, col=NA, pch=25, cex=1.2)
points(x=urban.pts[,"Muni_area"], y=urban.pts[,"Muni_width"], bg=grey.transparant, col=NA, pch=25, cex=1.2)

axis(side = 1, at = c(2,3,4,5,6,7,8,9,10,11,12), labels = c("2",NA,"4",NA,"6",NA,"8",NA,"10",NA,"12"), padj = 0, cex.axis=1.5)

mtext(expression(paste("Toepad Area (mm"^"2",")")), side=1, line=3.5, cex=1.5)
mtext("Average Lamellae Height (mm)", side=2, line=3, cex=1.5)

#Muni urban and forest averages 
pt1<-c(mean(forest.pts[,"Muni_area"]), mean(forest.pts[,"Muni_width"]))
pt2<-c(mean(urban.pts[,"Muni_area"]), mean(urban.pts[,"Muni_width"]))
segments(pt1[1], pt1[2], pt2[1], pt2[2])
points(pt1[1], pt1[2], bg="darkgreen", col="black", pch=25)
points(pt2[1], pt2[2], bg="gray", col="black", pch=25)


dev.off()



### Now consider relationships between pad length vs lam height vs lam count vs urban/forest add plots to supplement


#how is lamellae width correlated with toe pad length and habitat? 
out<-Anova(glm(log(dat.linear.raw[,"avelamwidth"])~log(dat.linear.raw[,"padlength"])*dat.field[,"Habitat_Category"]),  type="II")
out$`Pr(>Chisq)`[1] #pad length pval  6.602331e-17
out$`Pr(>Chisq)`[2] #habitat pval 0.06619929
out$`Pr(>Chisq)`[3] #interaction pval 0.5834027
#Pad length significantly correlated with lamellae width, and weaking with  habitat category, but there is no interaction between habitat and pad length affecting lamellae width


#how is lamellae count correlated with toe pad length and habitat? 
out<-Anova(glm(sqrt(dat.field[,"Lamellae_Count"])~log(dat.linear.raw[,"padlength"])*dat.field[,"Habitat_Category"]),  type="II")
out$`Pr(>Chisq)`[1] #pad length pval  0.0005279951
out$`Pr(>Chisq)`[2] #habitat pval 0.09278832
out$`Pr(>Chisq)`[3] #interaction pval 0.501353
#Pad length significantly correlated with lamellae count, but not habitat, and there is no interaction between habitat and pad length affecting lamellae count


pdf(file=file.path("Output/Plots/Linear/supp/Pad Length vs Lam Scatter.pdf"), width=4, height=8.3)
par(mfrow=c(2,1),mar=c(3,3.5,1,1), pty="s") 


plot(log(dat.linear.raw[,"padlength"]), sqrt(dat.field[,"Lamellae_Count"]), col="white", xlab=NA, ylab=NA, xaxt="n", yaxt="n", ylim=sqrt(c(16, 27)), xlim=log(c(2,5)))
abline(lm(sqrt(dat.field[dat.field$Habitat_Category=="forest","Lamellae_Count"])~log(dat.linear.raw[dat.field$Habitat_Category=="forest","padlength"])), col=green.transparant, lwd=3)
abline(lm(sqrt(dat.field[dat.field$Habitat_Category=="urban","Lamellae_Count"])~log(dat.linear.raw[dat.field$Habitat_Category=="urban","padlength"])), col=grey.transparant, lwd=3)

hpts<-chull(log(dat.linear.raw[dat.field$Habitat_Category=="forest","padlength"]), sqrt(dat.field[dat.field$Habitat_Category=="forest","Lamellae_Count"])) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(log(dat.linear.raw[dat.field$Habitat_Category=="forest","padlength"])[hpts], sqrt(dat.field[dat.field$Habitat_Category=="forest","Lamellae_Count"])[hpts], col=green.transparant) #plot the lines

hpts<-chull(log(dat.linear.raw[dat.field$Habitat_Category=="urban","padlength"]), sqrt(dat.field[dat.field$Habitat_Category=="urban","Lamellae_Count"])) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(log(dat.linear.raw[dat.field$Habitat_Category=="urban","padlength"])[hpts], sqrt(dat.field[dat.field$Habitat_Category=="urban","Lamellae_Count"])[hpts], col=grey.transparant) #plot the lines

points(log(dat.linear.raw[,"padlength"]), sqrt(dat.field[,"Lamellae_Count"]), col=HabColors, pch=19)

axis(side = 1, at = log(c(seq(2,5,by=0.5))), labels = c(seq(2,5,by=0.5)), padj = -0.8)
axis(side = 2, at = sqrt(c(seq(16,27,by=1))), labels = c("16",NA,"18",NA,"20",NA,"22",NA,"24",NA,"26",NA))

mtext("Toepad Length (mm)", side=1, line=2.2, cex=1.5)
mtext("Lamellae Count", side=2, line=2, cex=1.5)



out<-lm(sqrt(dat.field[dat.field$Habitat_Category=="forest","Lamellae_Count"])~log(dat.linear.raw[dat.field$Habitat_Category=="forest","padlength"]))
text(x=2.7, y=16.7, labels = paste("Forest Fit: y = ", round(out$coefficients[[2]], 2), "x + ",  round(out$coefficients[["(Intercept)"]], 2), sep=""), pos=4 )

out<-lm(sqrt(dat.field[dat.field$Habitat_Category=="urban","Lamellae_Count"])~log(dat.linear.raw[dat.field$Habitat_Category=="urban","padlength"]))
text(x=2.7, y=16, labels = paste("Urban Fit: y = ", round(out$coefficients[[2]], 2), "x + ",  round(out$coefficients[["(Intercept)"]], 2), sep=""), pos=4 )




plot(log(dat.linear.raw[,"padlength"]), log(dat.linear.raw[,"avelamwidth"]), col="white", xlab=NA, ylab=NA, xaxt="n", yaxt="n", xlim=log(c(2,5)), ylim=log(c(0.08,0.35)))
abline(lm(log(dat.linear.raw[dat.field$Habitat_Category=="forest","avelamwidth"])~log(dat.linear.raw[dat.field$Habitat_Category=="forest","padlength"])), col=green.transparant, lwd=3)
abline(lm(log(dat.linear.raw[dat.field$Habitat_Category=="urban","avelamwidth"])~log(dat.linear.raw[dat.field$Habitat_Category=="urban","padlength"])), col=grey.transparant, lwd=3)

hpts<-chull(log(dat.linear.raw[dat.field$Habitat_Category=="forest","padlength"]), log(dat.linear.raw[dat.field$Habitat_Category=="forest","avelamwidth"])) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(log(dat.linear.raw[dat.field$Habitat_Category=="forest","padlength"])[hpts], log(dat.linear.raw[dat.field$Habitat_Category=="forest","avelamwidth"])[hpts], col=green.transparant) #plot the lines

hpts<-chull(log(dat.linear.raw[dat.field$Habitat_Category=="urban","padlength"]), log(dat.linear.raw[dat.field$Habitat_Category=="urban","avelamwidth"])) #get list of outer points
hpts<-c(hpts, hpts[1]) #duplicate first point to close the polygon
lines(log(dat.linear.raw[dat.field$Habitat_Category=="urban","padlength"])[hpts], log(dat.linear.raw[dat.field$Habitat_Category=="urban","avelamwidth"])[hpts], col=grey.transparant) #plot the lines

points(log(dat.linear.raw[,"padlength"]), log(dat.linear.raw[,"avelamwidth"]), col=HabColors, pch=19)

axis(side = 1, at = log(c(seq(2,5,by=0.5))), label=seq(2,5,by=0.5), padj = -0.8)
axis(side = 2, at = log(c(seq(0.05,0.3,by=0.05))), label=c(NA,"0.1",NA,"0.2",NA,"0.3"), padj =0.8)

mtext("Toepad Length (mm)", side=1, line=2.2, cex=1.5)
mtext("Average Lamellae Height (mm)", side=2, line=2, cex=1.5)

out<-lm(log(dat.linear.raw[dat.field$Habitat_Category=="forest","avelamwidth"])~log(dat.linear.raw[dat.field$Habitat_Category=="forest","padlength"]))
text(x=3, y=0.025, labels = paste("Forest Fit: y = ", round(out$coefficients[[2]], 2), "x + ",  round(out$coefficients[["(Intercept)"]], 2), sep=""), pos=4 )

out<-lm(log(dat.linear.raw[dat.field$Habitat_Category=="urban","avelamwidth"])~log(dat.linear.raw[dat.field$Habitat_Category=="urban","padlength"]))
text(x=3, y=0.005, labels = paste("Urban Fit: y = ", round(out$coefficients[[2]], 2), "x + ",  round(out$coefficients[["(Intercept)"]], 2), sep=""), pos=4 )



dev.off()


#remove variables we no logner need 
rm(forest.pts)
rm(urban.pts)
rm(out)
rm(brks)
rm(hpts)
rm(pt1)
rm(pt2)
rm(CI)





######

